---
scenario:
  name: rootca
  test_sequence:
    - create
    - converge
    - idempotence
    - verify
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: rhel8
    image: docker.io/redhat/ubi8-init:latest
    pre_build_image: false
    dockerfile: ../../common/ubi8.dockerfile.j2
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /usr/share/crypto-policies/back-ends/FIPS:/etc/crypto-policies/back-ends:ro
    capabilities:
      - SYS_ADMIN
    command: "/usr/sbin/init"
    groups:
      - data
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false
verifier:
  name: ansible
