---
scenario:
  name: lint
  test_sequence:
    - lint
dependency:
  name: galaxy
driver:
  name: podman
lint: | 
  set -e
  echo "Run yamllint"
  yamllint .
  echo "Run ansible-lint"
  ansible-lint .
platforms:
  - name: instance
    image: docker.io/redhat/ubi9:9.1.0  #quay.io/centos/centos:stream8
    command: "/sbin/init"
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
verifier:
  name: ansible
