---
scenario:
  name: elasticsearch
  test_sequence:
    - create
    - converge
    - idempotence
    - verify
driver:
  name: podman
platforms:
  - &elasticsearch_platform
    name: esdata1
    image: docker.io/redhat/ubi8-init:latest
    pre_build_image: false
    dockerfile: ../../common/ubi8.dockerfile.j2
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /usr/share/crypto-policies/back-ends/FIPS:/etc/crypto-policies/back-ends:ro
    capabilities:
      - SYS_ADMIN
    command: "/usr/sbin/init"
    groups:
      - data
    network: net2
  - <<: *elasticsearch_platform
    name: esdata2
  - <<: *elasticsearch_platform
    name: esdata3
  - <<: *elasticsearch_platform
    name: kibana1
    published_ports:
      - 0.0.0.0:5601:5601/tcp
    groups:
      - kibana
  - <<: *elasticsearch_platform
    name: logstash1
    groups:
      - logstash
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: profile_tasks, timer, yaml
      verbosity: 0
    ssh_connection:
      pipelining: false
verifier:
  name: ansible
